################################################################################
################################################################################
################################################################################
# Author: Sean Tronsen
# Date: 11172023
#
# COMPILE DOCUMENTS WHEN A NEW SEMANTIC VERSIONS IS AVAILABLE
################################################################################
################################################################################
################################################################################
name: compile-document
on:
  push:
    tags:
      - "v*.*.*"
env:
  BUILD_SOURCES: resume.tex
  BUILD_TARGETS: resume.pdf
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: grab repository files
        uses: actions/checkout@v4
      - name: Compile LaTeX sources
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.BUILD_SOURCES }}
      - name: Release PDFs
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BUILD_TARGETS }}
