name: compile-document
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Release New PDF
        uses: softprops/action-gh-release@v1
        with:
          files: "*.pdf"
